from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PostgresMigration:
    version: int
    name: str
    sql: str


POSTGRES_MIGRATIONS = (
    PostgresMigration(
        1,
        "bootstrap schema metadata",
        """
        CREATE TABLE IF NOT EXISTS nntpintel_schema_version (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """,
    ),
    PostgresMigration(
        2,
        "production core schema and observation partitions",
        """
        CREATE TABLE IF NOT EXISTS servers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            host TEXT NOT NULL UNIQUE,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS endpoints (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            port INTEGER NOT NULL,
            transport TEXT NOT NULL,
            starttls BOOLEAN NOT NULL DEFAULT FALSE,
            interval_seconds INTEGER NOT NULL DEFAULT 900,
            timeout_seconds DOUBLE PRECISION NOT NULL DEFAULT 10.0,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            consecutive_failures INTEGER NOT NULL DEFAULT 0,
            next_probe_at TIMESTAMPTZ,
            last_probe_at TIMESTAMPTZ,
            UNIQUE(server_id, port, transport, starttls)
        );

        CREATE TABLE IF NOT EXISTS hierarchies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE IF NOT EXISTS newsgroups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            hierarchy_id BIGINT NOT NULL REFERENCES hierarchies(id),
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE IF NOT EXISTS propagation_articles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id TEXT NOT NULL UNIQUE,
            newsgroup TEXT,
            article_date TIMESTAMPTZ,
            first_registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS observations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            success BOOLEAN NOT NULL,
            connect_ms DOUBLE PRECISION,
            greeting_code INTEGER,
            greeting TEXT,
            posting_allowed BOOLEAN,
            mode_reader_code INTEGER,
            mode_reader_response TEXT,
            capabilities_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            tls_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            error TEXT,
            raw_json JSONB NOT NULL,
            PRIMARY KEY(id, observed_at)
        ) PARTITION BY RANGE (observed_at);

        CREATE TABLE IF NOT EXISTS observations_default
            PARTITION OF observations DEFAULT;

        CREATE TABLE IF NOT EXISTS group_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            newsgroup_id BIGINT NOT NULL REFERENCES newsgroups(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            high_water BIGINT,
            low_water BIGINT,
            posting_status TEXT,
            description TEXT,
            PRIMARY KEY(id, observed_at),
            UNIQUE(endpoint_id, newsgroup_id, observed_at)
        ) PARTITION BY RANGE (observed_at);

        CREATE TABLE IF NOT EXISTS group_snapshots_default
            PARTITION OF group_snapshots DEFAULT;

        CREATE TABLE IF NOT EXISTS group_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            newsgroup_id BIGINT NOT NULL REFERENCES newsgroups(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            event_type TEXT NOT NULL,
            detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            PRIMARY KEY(id, observed_at)
        ) PARTITION BY RANGE (observed_at);

        CREATE TABLE IF NOT EXISTS group_events_default
            PARTITION OF group_events DEFAULT;

        CREATE TABLE IF NOT EXISTS propagation_observations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            article_id BIGINT NOT NULL REFERENCES propagation_articles(id) ON DELETE CASCADE,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            present BOOLEAN NOT NULL,
            method TEXT NOT NULL DEFAULT 'stat',
            response_code INTEGER,
            error TEXT,
            PRIMARY KEY(id, observed_at),
            UNIQUE(article_id, endpoint_id, observed_at)
        ) PARTITION BY RANGE (observed_at);

        CREATE TABLE IF NOT EXISTS propagation_observations_default
            PARTITION OF propagation_observations DEFAULT;

        CREATE INDEX IF NOT EXISTS idx_endpoints_due
            ON endpoints(enabled, next_probe_at);
        CREATE INDEX IF NOT EXISTS idx_observations_endpoint_time
            ON observations(endpoint_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_group_snapshots_group_time
            ON group_snapshots(newsgroup_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_group_events_endpoint_time
            ON group_events(endpoint_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_propagation_observations_article_time
            ON propagation_observations(article_id, observed_at ASC);
        CREATE INDEX IF NOT EXISTS idx_propagation_observations_endpoint_time
            ON propagation_observations(endpoint_id, observed_at DESC);
        """,
    ),
)


def apply_postgres_migrations(conn) -> int:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS nntpintel_schema_version (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    rows = conn.execute("SELECT version FROM nntpintel_schema_version").fetchall()
    applied = {int(row["version"]) for row in rows}

    for migration in POSTGRES_MIGRATIONS:
        if migration.version in applied:
            continue
        conn.execute(migration.sql)
        conn.execute(
            "INSERT INTO nntpintel_schema_version(version, name) VALUES (%s, %s)",
            (migration.version, migration.name),
        )
    conn.commit()
    return POSTGRES_MIGRATIONS[-1].version if POSTGRES_MIGRATIONS else 0
