from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PostgresMigration:
    version: int
    name: str
    sql: str


POSTGRES_MIGRATIONS = (
    PostgresMigration(
        1,
        "bootstrap schema metadata",
        """
        CREATE TABLE IF NOT EXISTS nntpintel_schema_version (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """,
    ),
    PostgresMigration(
        2,
        "production core schema and observation partitions",
        """
        CREATE TABLE IF NOT EXISTS servers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            host TEXT NOT NULL UNIQUE,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS endpoints (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            port INTEGER NOT NULL,
            transport TEXT NOT NULL,
            starttls BOOLEAN NOT NULL DEFAULT FALSE,
            interval_seconds INTEGER NOT NULL DEFAULT 900,
            timeout_seconds DOUBLE PRECISION NOT NULL DEFAULT 10.0,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            consecutive_failures INTEGER NOT NULL DEFAULT 0,
            next_probe_at TIMESTAMPTZ,
            last_probe_at TIMESTAMPTZ,
            UNIQUE(server_id, port, transport, starttls)
        );

        CREATE TABLE IF NOT EXISTS hierarchies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE IF NOT EXISTS newsgroups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            hierarchy_id BIGINT NOT NULL REFERENCES hierarchies(id),
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE IF NOT EXISTS propagation_articles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id TEXT NOT NULL UNIQUE,
            newsgroup TEXT,
            article_date TIMESTAMPTZ,
            first_registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS observations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            success BOOLEAN NOT NULL,
            connect_ms DOUBLE PRECISION,
            greeting_code INTEGER,
            greeting TEXT,
            posting_allowed BOOLEAN,
            mode_reader_code INTEGER,
            mode_reader_response TEXT,
            capabilities_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            tls_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            error TEXT,
            raw_json JSONB NOT NULL,
            PRIMARY KEY(id, observed_at)
        ) PARTITION BY RANGE (observed_at);

        CREATE TABLE IF NOT EXISTS observations_default PARTITION OF observations DEFAULT;

        CREATE TABLE IF NOT EXISTS group_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            newsgroup_id BIGINT NOT NULL REFERENCES newsgroups(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            high_water BIGINT,
            low_water BIGINT,
            posting_status TEXT,
            description TEXT,
            PRIMARY KEY(id, observed_at),
            UNIQUE(endpoint_id, newsgroup_id, observed_at)
        ) PARTITION BY RANGE (observed_at);
        CREATE TABLE IF NOT EXISTS group_snapshots_default PARTITION OF group_snapshots DEFAULT;

        CREATE TABLE IF NOT EXISTS group_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            newsgroup_id BIGINT NOT NULL REFERENCES newsgroups(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            event_type TEXT NOT NULL,
            detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            PRIMARY KEY(id, observed_at)
        ) PARTITION BY RANGE (observed_at);
        CREATE TABLE IF NOT EXISTS group_events_default PARTITION OF group_events DEFAULT;

        CREATE TABLE IF NOT EXISTS propagation_observations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            article_id BIGINT NOT NULL REFERENCES propagation_articles(id) ON DELETE CASCADE,
            endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            present BOOLEAN NOT NULL,
            method TEXT NOT NULL DEFAULT 'stat',
            response_code INTEGER,
            error TEXT,
            PRIMARY KEY(id, observed_at),
            UNIQUE(article_id, endpoint_id, observed_at)
        ) PARTITION BY RANGE (observed_at);
        CREATE TABLE IF NOT EXISTS propagation_observations_default PARTITION OF propagation_observations DEFAULT;

        CREATE INDEX IF NOT EXISTS idx_endpoints_due ON endpoints(enabled, next_probe_at);
        CREATE INDEX IF NOT EXISTS idx_observations_endpoint_time ON observations(endpoint_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_group_snapshots_group_time ON group_snapshots(newsgroup_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_group_events_endpoint_time ON group_events(endpoint_id, observed_at DESC);
        CREATE INDEX IF NOT EXISTS idx_propagation_observations_article_time ON propagation_observations(article_id, observed_at ASC);
        CREATE INDEX IF NOT EXISTS idx_propagation_observations_endpoint_time ON propagation_observations(endpoint_id, observed_at DESC);
        """,
    ),
    PostgresMigration(
        3,
        "server availability and latency rollups",
        """
        CREATE TABLE IF NOT EXISTS server_observation_rollups (
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            resolution TEXT NOT NULL CHECK (resolution IN ('hour', 'day')),
            bucket_start TIMESTAMPTZ NOT NULL,
            observation_count BIGINT NOT NULL,
            success_count BIGINT NOT NULL,
            failure_count BIGINT NOT NULL,
            availability_ratio DOUBLE PRECISION,
            connect_ms_count BIGINT NOT NULL,
            connect_ms_avg DOUBLE PRECISION,
            connect_ms_min DOUBLE PRECISION,
            connect_ms_max DOUBLE PRECISION,
            generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(server_id, resolution, bucket_start),
            CHECK (observation_count >= 0),
            CHECK (success_count >= 0),
            CHECK (failure_count >= 0),
            CHECK (connect_ms_count >= 0),
            CHECK (success_count + failure_count = observation_count),
            CHECK (availability_ratio IS NULL OR (availability_ratio >= 0 AND availability_ratio <= 1))
        );
        CREATE INDEX IF NOT EXISTS idx_server_observation_rollups_resolution_time ON server_observation_rollups(resolution, bucket_start DESC);
        CREATE INDEX IF NOT EXISTS idx_server_observation_rollups_server_time ON server_observation_rollups(server_id, bucket_start DESC);
        """,
    ),
    PostgresMigration(
        4,
        "allow monthly server observation rollups",
        """
        ALTER TABLE server_observation_rollups DROP CONSTRAINT IF EXISTS server_observation_rollups_resolution_check;
        ALTER TABLE server_observation_rollups ADD CONSTRAINT server_observation_rollups_resolution_check CHECK (resolution IN ('hour', 'day', 'month'));
        """,
    ),
    PostgresMigration(
        5,
        "server TLS and capability rollups",
        """
        CREATE TABLE IF NOT EXISTS server_protocol_rollups (
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            resolution TEXT NOT NULL CHECK (resolution IN ('hour', 'day', 'month')),
            bucket_start TIMESTAMPTZ NOT NULL,
            observation_count BIGINT NOT NULL,
            tls_enabled_count BIGINT NOT NULL,
            tls_ratio DOUBLE PRECISION,
            capabilities_observed_count BIGINT NOT NULL,
            capability_entry_count BIGINT NOT NULL,
            generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(server_id, resolution, bucket_start),
            CHECK (observation_count >= 0),
            CHECK (tls_enabled_count >= 0 AND tls_enabled_count <= observation_count),
            CHECK (capabilities_observed_count >= 0 AND capabilities_observed_count <= observation_count),
            CHECK (capability_entry_count >= 0),
            CHECK (tls_ratio IS NULL OR (tls_ratio >= 0 AND tls_ratio <= 1))
        );

        CREATE TABLE IF NOT EXISTS server_protocol_value_rollups (
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            resolution TEXT NOT NULL CHECK (resolution IN ('hour', 'day', 'month')),
            bucket_start TIMESTAMPTZ NOT NULL,
            kind TEXT NOT NULL CHECK (kind IN ('tls_protocol', 'tls_cipher', 'capability')),
            value TEXT NOT NULL,
            occurrence_count BIGINT NOT NULL CHECK (occurrence_count > 0),
            generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(server_id, resolution, bucket_start, kind, value)
        );

        CREATE INDEX IF NOT EXISTS idx_server_protocol_rollups_resolution_time
            ON server_protocol_rollups(resolution, bucket_start DESC);
        CREATE INDEX IF NOT EXISTS idx_server_protocol_values_kind_time
            ON server_protocol_value_rollups(kind, resolution, bucket_start DESC);
        """,
    ),
    PostgresMigration(
        6,
        "server group hierarchy and event rollups",
        """
        CREATE TABLE IF NOT EXISTS server_group_rollups (
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            resolution TEXT NOT NULL CHECK (resolution IN ('hour', 'day', 'month')),
            bucket_start TIMESTAMPTZ NOT NULL,
            inventory_count BIGINT NOT NULL,
            snapshot_count BIGINT NOT NULL,
            observed_group_count BIGINT NOT NULL,
            observed_hierarchy_count BIGINT NOT NULL,
            event_count BIGINT NOT NULL,
            generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(server_id, resolution, bucket_start),
            CHECK (inventory_count >= 0),
            CHECK (snapshot_count >= 0),
            CHECK (observed_group_count >= 0),
            CHECK (observed_hierarchy_count >= 0),
            CHECK (event_count >= 0)
        );

        CREATE TABLE IF NOT EXISTS server_group_value_rollups (
            server_id BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
            resolution TEXT NOT NULL CHECK (resolution IN ('hour', 'day', 'month')),
            bucket_start TIMESTAMPTZ NOT NULL,
            kind TEXT NOT NULL CHECK (kind IN ('posting_status', 'event_type')),
            value TEXT NOT NULL,
            occurrence_count BIGINT NOT NULL CHECK (occurrence_count > 0),
            generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(server_id, resolution, bucket_start, kind, value)
        );

        CREATE INDEX IF NOT EXISTS idx_server_group_rollups_resolution_time
            ON server_group_rollups(resolution, bucket_start DESC);
        CREATE INDEX IF NOT EXISTS idx_server_group_values_kind_time
            ON server_group_value_rollups(kind, resolution, bucket_start DESC);
        """,
    ),
)


def apply_postgres_migrations(conn) -> int:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS nntpintel_schema_version (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    rows = conn.execute("SELECT version FROM nntpintel_schema_version").fetchall()
    applied = {int(row["version"]) for row in rows}

    for migration in POSTGRES_MIGRATIONS:
        if migration.version in applied:
            continue
        conn.execute(migration.sql)
        conn.execute(
            "INSERT INTO nntpintel_schema_version(version, name) VALUES (%s, %s)",
            (migration.version, migration.name),
        )
    conn.commit()
    return POSTGRES_MIGRATIONS[-1].version if POSTGRES_MIGRATIONS else 0
